export interface TickerInfo {
  name: string;
  logo: string;
}

export const tickerData: Record<string, TickerInfo> = {
  ITMG: { name: "Indo Tambangraya Megah Tbk.", logo: "https://assets.stockbit.com/logos/companies/ITMG.png" },
  NCKL: { name: "Trimegah Bangun Persada Tbk.", logo: "https://assets.stockbit.com/logos/companies/NCKL.png" },
  ITMA: { name: "Sumber Energi Andalan Tbk.", logo: "https://assets.stockbit.com/logos/companies/ITMA.png" },
  BRIS: { name: "Bank Syariah Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/BRIS.png" },
  ERAA: { name: "Erajaya Swasembada Tbk.", logo: "https://assets.stockbit.com/logos/companies/ERAA.png" },
  ACES: { name: "Aspirasi Hidup Indonesia Tbk", logo: "https://assets.stockbit.com/logos/companies/ACES-NEW.png" },
  HEAL: { name: "Medikaloka Hermina Tbk.", logo: "https://assets.stockbit.com/logos/companies/HEAL.png" },
  MYOR: { name: "Mayora Indah Tbk", logo: "https://assets.stockbit.com/logos/companies/MYOR.png" },
  DAAZ: { name: "Daaz Bara Lestari Tbk.", logo: "https://assets.stockbit.com/logos/companies/DAAZ.png?version=1728638262441389197" },
  DMAS: { name: "Puradelta Lestari Tbk", logo: "https://assets.stockbit.com/logos/companies/DMAS.png" },
  GIAA: { name: "Garuda Indonesia (Persero) Tbk.", logo: "https://assets.stockbit.com/logos/companies/GIAA.png" },
  SCMA: { name: "Surya Citra Media Tbk.", logo: "https://assets.stockbit.com/logos/companies/SCMA.png" },
  ERAL: { name: "Sinar Eka Selaras Tbk.", logo: "https://assets.stockbit.com/logos/companies/ERAL.png" },
  NSSS: { name: "Nusantara Sawit Sejahtera Tbk.", logo: "https://assets.stockbit.com/logos/companies/NSSS.png" },
  PTBA: { name: "Bukit Asam Tbk.", logo: "https://assets.stockbit.com/logos/companies/PTBA.png" },
  BREN: { name: "Barito Renewables Energy Tbk.", logo: "https://assets.stockbit.com/logos/companies/BREN.png" },
  PSAB: { name: "J Resources Asia Pasifik Tbk.", logo: "https://assets.stockbit.com/logos/companies/PSAB.png" },
  PNBN: { name: "Bank Pan Indonesia Tbk", logo: "https://assets.stockbit.com/logos/companies/PNBN.png" },
  AKRA: { name: "AKR Corporindo Tbk.", logo: "https://assets.stockbit.com/logos/companies/AKRA.png" },
  KOKA: { name: "Koka Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/KOKA.png" },
  GGRM: { name: "Gudang Garam Tbk.", logo: "https://assets.stockbit.com/logos/companies/GGRM.png" },
  ASPR: { name: "Asia Pramulia Tbk.", logo: "https://assets.stockbit.com/logos/companies/ASPR.png?version=1750650695517624354" },
  BIRD: { name: "Blue Bird Tbk.", logo: "https://assets.stockbit.com/logos/companies/BIRD.png" },
  MLPL: { name: "Multipolar Tbk.", logo: "https://assets.stockbit.com/logos/companies/MLPL.png" },
  FOLK: { name: "Multi Garam Utama Tbk.", logo: "https://assets.stockbit.com/logos/companies/FOLK.png" },
  TPMA: { name: "Trans Power Marine Tbk.", logo: "https://assets.stockbit.com/logos/companies/TPMA.png" },
  WINS: { name: "Wintermar Offshore Marine Tbk.", logo: "https://assets.stockbit.com/logos/companies/WINS.png" },
  KKGI: { name: "Resource Alam Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/KKGI.png" },
  PADA: { name: "Personel Alih Daya Tbk.", logo: "https://assets.stockbit.com/logos/companies/PADA.png" },
  MHKI: { name: "Multi Hanna Kreasindo Tbk.", logo: "https://assets.stockbit.com/logos/companies/MHKI.png" },
  KRYA: { name: "Bangun Karya Perkasa Jaya Tbk.", logo: "https://assets.stockbit.com/logos/companies/KRYA.png" },
  JARR: { name: "Jhonlin Agro Raya Tbk.", logo: "https://assets.stockbit.com/logos/companies/JARR.png" },
  GJTL: { name: "Gajah Tunggal Tbk.", logo: "https://assets.stockbit.com/logos/companies/GJTL.png" },
  BMTR: { name: "Global Mediacom Tbk.", logo: "https://assets.stockbit.com/logos/companies/BMTR.png" },
  TOSK: { name: "Topindo Solusi Komunika Tbk.", logo: "https://assets.stockbit.com/logos/companies/TOSK.png" },
  CNMA: { name: "Nusantara Sejahtera Raya Tbk.", logo: "https://assets.stockbit.com/logos/companies/CNMA.png" },
  ALII: { name: "Ancara Logistics Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/ALII.png" },
  AALI: { name: "Astra Agro Lestari Tbk.", logo: "https://assets.stockbit.com/logos/companies/AALI.png" },
  UNIQ: { name: "Ulima Nitra Tbk", logo: "https://assets.stockbit.com/logos/companies/UNIQ.png" },
  BANK: { name: "Bank Aladin Syariah Tbk.", logo: "https://assets.stockbit.com/logos/companies/BANK.png" },
  DOSS: { name: "Global Sukses Digital Tbk", logo: "https://assets.stockbit.com/logos/companies/DOSS.png" },
  DNAR: { name: "Bank Oke Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/DNAR.png" },
  DGNS: { name: "Diagnos Laboratorium Utama Tbk", logo: "https://assets.stockbit.com/logos/companies/DGNS.png" },
  DWGL: { name: "Dwi Guna Laksana Tbk.", logo: "https://assets.stockbit.com/logos/companies/DWGL.png" },
  CTTH: { name: "Citatah Tbk.", logo: "https://assets.stockbit.com/logos/companies/CTTH.png" },
  BNBA: { name: "Bank Bumi Arta Tbk.", logo: "https://assets.stockbit.com/logos/companies/BNBA.png" },
  FWCT: { name: "Wijaya Cahaya Timber Tbk.", logo: "https://assets.stockbit.com/logos/companies/FWCT.png" },
  HAIS: { name: "Hasnur Internasional Shipping Tbk", logo: "https://assets.stockbit.com/logos/companies/HAIS.png" },
  GRPM: { name: "Graha Prima Mentari Tbk.", logo: "https://assets.stockbit.com/logos/companies/GRPM.png" },
  TMPO: { name: "Tempo Inti Media Tbk.", logo: "https://assets.stockbit.com/logos/companies/TMPO.png" },
  SMLE: { name: "Sinergi Multi Lestarindo Tbk.", logo: "https://assets.stockbit.com/logos/companies/SMLE.png" },
  SAME: { name: "Sarana Meditama Metropolitan Tbk", logo: "https://assets.stockbit.com/logos/companies/SAME.png" },
  ISEA: { name: "Indo American Seafoods Tbk", logo: "https://assets.stockbit.com/logos/companies/ISEA.png" },
  SRSN: { name: "Indo Acidatama Tbk", logo: "https://assets.stockbit.com/logos/companies/SRSN.png" },
  SSTM: { name: "Sunson Textile Manufacture Tbk", logo: "https://assets.stockbit.com/logos/companies/SSTM.png" },
  BGTG: { name: "Bank Ganesha Tbk.", logo: "https://assets.stockbit.com/logos/companies/BGTG.png" },
  JIHD: { name: "Jakarta International Hotels & Development Tbk", logo: "https://assets.stockbit.com/logos/companies/JIHD.png" },
  JAST: { name: "Jasnita Telekomindo Tbk.", logo: "https://assets.stockbit.com/logos/companies/JAST.png" },
  MDLA: { name: "Medela Potentia Tbk.", logo: "https://assets.stockbit.com/logos/companies/MDLA.png?version=1741748745584611653" },
  CHEM: { name: "Chemstar Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/CHEM.png" },
  SDMU: { name: "Sidomulyo Selaras Tbk.", logo: "https://assets.stockbit.com/logos/companies/SDMU.png" },
  MCOR: { name: "Bank China Construction Bank Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/MCOR.png" },
  MLIA: { name: "Mulia Industrindo Tbk.", logo: "https://assets.stockbit.com/logos/companies/MLIA.png" },
  MEDS: { name: "Hetzer Medical Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/MEDS.png" },
  NAYZ: { name: "Hassana Boga Sejahtera Tbk.", logo: "https://assets.stockbit.com/logos/companies/NAYZ.png" },
  BELI: { name: "Global Digital Niaga Tbk.", logo: "https://assets.stockbit.com/logos/companies/BELI.png" },
  BCIP: { name: "Bumi Citra Permai Tbk.", logo: "https://assets.stockbit.com/logos/companies/BCIP.png" },
  OPMS: { name: "Optima Prima Metal Sinergi Tbk", logo: "https://assets.stockbit.com/logos/companies/OPMS.png" },
  NISP: { name: "Bank OCBC NISP Tbk.", logo: "https://assets.stockbit.com/logos/companies/NISP.png" },
  OBMD: { name: "OBM Drilchem Tbk.", logo: "https://assets.stockbit.com/logos/companies/OBMD.png" },
  NIKL: { name: "Pelat Timah Nusantara Tbk.", logo: "https://assets.stockbit.com/logos/companies/NIKL.png" },
  PNBS: { name: "Bank Panin Dubai Syariah Tbk.", logo: "https://assets.stockbit.com/logos/companies/PNBS.png" },
  TRON: { name: "Teknologi Karya Digital Nusa Tbk.", logo: "https://assets.stockbit.com/logos/companies/TRON.png" },
  AGRS: { name: "Bank IBK Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/AGRS.png" },
  WEHA: { name: "WEHA Transportasi Indonesia Tbk", logo: "https://assets.stockbit.com/logos/companies/WEHA.png" },
  ZATA: { name: "Bersama Zatta Jaya Tbk.", logo: "https://assets.stockbit.com/logos/companies/ZATA.png" },
  WSBP: { name: "Waskita Beton Precast Tbk.", logo: "https://assets.stockbit.com/logos/companies/WSBP.png" },
  AGRO: { name: "Bank Raya Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/AGRO.png" },
  PGUN: { name: "Pradiksi Gunatama Tbk.", logo: "https://assets.stockbit.com/logos/companies/PGUN.png" },
  NAIK: { name: "Adiwarna Anugerah Abadi Tbk.", logo: "https://assets.stockbit.com/logos/companies/NAIK.png?version=1730866518209286014" },
  MDLN: { name: "Modernland Realty Ltd. Tbk", logo: "https://assets.stockbit.com/logos/companies/MDLN.png" },
  MDIA: { name: "Intermedia Capital Tbk", logo: "https://assets.stockbit.com/logos/companies/MDIA.png" },
  JAYA: { name: "Armada Berjaya Trans Tbk.", logo: "https://assets.stockbit.com/logos/companies/JAYA.png" },
  STRK: { name: "Lovina Beach Brewery Tbk.", logo: "https://assets.stockbit.com/logos/companies/STRK.png" },
  SOTS: { name: "Satria Mega Kencana Tbk.", logo: "https://assets.stockbit.com/logos/companies/SOTS.png" },
  HILL: { name: "Hillcon Tbk.", logo: "https://assets.stockbit.com/logos/companies/HILL.png" },
  ELIT: { name: "Data Sinergitama Jaya Tbk.", logo: "https://assets.stockbit.com/logos/companies/ELIT.png" },
  TAMU: { name: "Pelayaran Tamarin Samudra Tbk", logo: "https://assets.stockbit.com/logos/companies/TAMU.png" },
  CLEO: { name: "Sariguna Primatirta Tbk", logo: "https://assets.stockbit.com/logos/companies/CLEO.png" },
  BDKR: { name: "Berdikari Pondasi Perkasa Tbk.", logo: "https://assets.stockbit.com/logos/companies/BDKR.png" },
  BABP: { name: "Bank MNC Internasional Tbk.", logo: "https://assets.stockbit.com/logos/companies/BABP.png" },
  VIVA: { name: "Visi Media Asia Tbk.", logo: "https://assets.stockbit.com/logos/companies/VIVA.png" },
  KDTN: { name: "Puri Sentul Permai Tbk.", logo: "https://assets.stockbit.com/logos/companies/KDTN.png" },
  INDO: { name: "Royalindo Investa Wijaya Tbk", logo: "https://assets.stockbit.com/logos/companies/INDO.png" },
  ARTO: { name: "Bank Jago Tbk.", logo: "https://assets.stockbit.com/logos/companies/ARTO.png" },
  MNCN: { name: "Media Nusantara Citra Tbk.", logo: "https://assets.stockbit.com/logos/companies/MNCN.png" },
  ADCP: { name: "Adhi Commuter Properti Tbk.", logo: "https://assets.stockbit.com/logos/companies/ADCP.png" },
  POWR: { name: "Cikarang Listrindo Tbk.", logo: "https://assets.stockbit.com/logos/companies/POWR.png" },
  ARNA: { name: "Arwana Citramulia Tbk.", logo: "https://assets.stockbit.com/logos/companies/ARNA.png" },
  WMUU: { name: "Widodo Makmur Unggas Tbk", logo: "https://assets.stockbit.com/logos/companies/WMUU.png" },
  RSCH: { name: "Charlie Hospital Semarang Tbk.", logo: "https://assets.stockbit.com/logos/companies/RSCH.png" },
  APLN: { name: "Agung Podomoro Land Tbk.", logo: "https://assets.stockbit.com/logos/companies/APLN.png" },
  KETR: { name: "Ketrosden Triasmitra Tbk.", logo: "https://assets.stockbit.com/logos/companies/KETR.png" },
  LIVE: { name: "Homeco Victoria Makmur Tbk.", logo: "https://assets.stockbit.com/logos/companies/LIVE.png" },
  MSTI: { name: "Mastersystem Infotama Tbk.", logo: "https://assets.stockbit.com/logos/companies/MSTI.png" },
  BSML: { name: "Bintang Samudera Mandiri Lines Tbk.", logo: "https://assets.stockbit.com/logos/companies/BSML.png" },
  MPXL: { name: "MPX Logistics International Tbk.", logo: "https://assets.stockbit.com/logos/companies/MPXL.png" },
  AYAM: { name: "Janu Putra Sejahtera Tbk.", logo: "https://assets.stockbit.com/logos/companies/AYAM.png" },
  WEGE: { name: "Wijaya Karya Bangunan Gedung Tbk.", logo: "https://assets.stockbit.com/logos/companies/WEGE.png" },
  PWON: { name: "Pakuwon Jati Tbk.", logo: "https://assets.stockbit.com/logos/companies/PWON.png" },
  NRCA: { name: "Nusa Raya Cipta Tbk", logo: "https://assets.stockbit.com/logos/companies/NRCA.png" },
  PEGE: { name: "Panca Global Kapital Tbk.", logo: "https://assets.stockbit.com/logos/companies/PEGE.png" },
  NATO: { name: "Olympus Strategic Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/NATO.png?version=1771406131675599387" },
  NASI: { name: "Wahana Inti Makmur Tbk.", logo: "https://assets.stockbit.com/logos/companies/NASI.png" },
  BBRM: { name: "Pelayaran National Bina Buana Raya Tbk.", logo: "https://assets.stockbit.com/logos/companies/BBRM.png" },
  BELL: { name: "Trisula Textile Industries Tbk", logo: "https://assets.stockbit.com/logos/companies/BELL.png" },
  BDMN: { name: "Bank Danamon Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/BDMN.png" },
  KPIG: { name: "MNC Tourism Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/KPIG.png" },
  MGLV: { name: "Panca Anugrah Wisesa Tbk", logo: "https://assets.stockbit.com/logos/companies/MGLV.png" },
  BEST: { name: "Bekasi Fajar Industrial Estate Tbk.", logo: "https://assets.stockbit.com/logos/companies/BEST.png" },
  PPRE: { name: "PP Presisi Tbk.", logo: "https://assets.stockbit.com/logos/companies/PPRE.png" },
  TOTL: { name: "Total Bangun Persada Tbk.", logo: "https://assets.stockbit.com/logos/companies/TOTL.png" },
  BCAP: { name: "MNC Kapital Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/BCAP.png" },
  MBMA: { name: "Merdeka Battery Materials Tbk.", logo: "https://assets.stockbit.com/logos/companies/MBMA.png" },
  RAJA: { name: "Rukun Raharja Tbk.", logo: "https://assets.stockbit.com/logos/companies/RAJA.png" },
  OMED: { name: "Jayamas Medica Industri Tbk.", logo: "https://assets.stockbit.com/logos/companies/OMED.png" },
  KOTA: { name: "DMS Propertindo Tbk.", logo: "https://assets.stockbit.com/logos/companies/KOTA.png" },
  MARK: { name: "Mark Dynamics Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/MARK.png" },
  BULL: { name: "Buana Lintas Lautan Tbk.", logo: "https://assets.stockbit.com/logos/companies/BULL.png" },
  SINI: { name: "Singaraja Putra Tbk.", logo: "https://assets.stockbit.com/logos/companies/SINI.png" },
  PNLF: { name: "Panin Financial Tbk.", logo: "https://assets.stockbit.com/logos/companies/PNLF.png" },
  IATA: { name: "MNC Energy Investments Tbk.", logo: "https://assets.stockbit.com/logos/companies/IATA.png" },
  CTRA: { name: "Ciputra Development Tbk.", logo: "https://assets.stockbit.com/logos/companies/CTRA.png" },
  BFIN: { name: "BFI Finance Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/BFIN.png" },
  PGAS: { name: "Perusahaan Gas Negara Tbk.", logo: "https://assets.stockbit.com/logos/companies/PGAS.png" },
  ASII: { name: "Astra International Tbk.", logo: "https://assets.stockbit.com/logos/companies/ASII.png" },
  TLKM: { name: "PT Telkom Indonesia (Persero) Tbk", logo: "https://assets.stockbit.com/logos/companies/TLKM.png" },
  ISAT: { name: "Indosat Tbk", logo: "https://assets.stockbit.com/logos/companies/ISAT.png" },
  BRPT: { name: "Barito Pacific Tbk.", logo: "https://assets.stockbit.com/logos/companies/BRPT.png" },
  INDF: { name: "Indofood Sukses Makmur Tbk.", logo: "https://assets.stockbit.com/logos/companies/INDF.png" },
  DSSA: { name: "Dian Swastatika Sentosa Tbk", logo: "https://assets.stockbit.com/logos/companies/DSSA.png" },
  LAPD: { name: "Leyand International Tbk.", logo: "https://assets.stockbit.com/logos/companies/LAPD.png" },
  LEAD: { name: "Logindo Samudramakmur Tbk.", logo: "https://assets.stockbit.com/logos/companies/LEAD.png" },
  GTSI: { name: "GTS Internasional Tbk", logo: "https://assets.stockbit.com/logos/companies/GTSI.png" },
  PPGL: { name: "Prima Globalindo Logistik Tbk.", logo: "https://assets.stockbit.com/logos/companies/PPGL.png" },
  IPCC: { name: "Indonesia Kendaraan Terminal Tbk.", logo: "https://assets.stockbit.com/logos/companies/IPCC.png?version=1730190669123413796" },
  INPC: { name: "Bank Artha Graha Internasional Tbk.", logo: "https://assets.stockbit.com/logos/companies/INPC.png" },
  CENT: { name: "Centratama Telekomunikasi Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/CENT.png" },
  FAST: { name: "Fast Food Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/FAST.png" },
  FITT: { name: "Hotel Fitra International Tbk.", logo: "https://assets.stockbit.com/logos/companies/FITT.png" },
  TKIM: { name: "Pabrik Kertas Tjiwi Kimia Tbk.", logo: "https://assets.stockbit.com/logos/companies/TKIM.png" },
  HGII: { name: "Hero Global Investment Tbk.", logo: "https://assets.stockbit.com/logos/companies/HGII.png?version=1734504130325627272" },
  GGRP: { name: "Gunung Raja Paksi Tbk", logo: "https://assets.stockbit.com/logos/companies/GGRP.png" },
  GEMS: { name: "Golden Energy Mines Tbk.", logo: "https://assets.stockbit.com/logos/companies/GEMS.png" },
  DOOH: { name: "Era Media Sejahtera Tbk.", logo: "https://assets.stockbit.com/logos/companies/DOOH.png" },
  CSIS: { name: "Cahayasakti Investindo Sukses Tbk", logo: "https://assets.stockbit.com/logos/companies/CSIS.png" },
  CMNT: { name: "Cemindo Gemilang Tbk.", logo: "https://assets.stockbit.com/logos/companies/CMNT.png" },
  BTPS: { name: "Bank BTPN Syariah Tbk", logo: "https://assets.stockbit.com/logos/companies/BTPS.png" },
  ESTA: { name: "Esta Multi Usaha Tbk.", logo: "https://assets.stockbit.com/logos/companies/ESTA.png" },
  DPUM: { name: "Dua Putra Utama Makmur Tbk", logo: "https://assets.stockbit.com/logos/companies/DPUM.png" },
  WOOD: { name: "Integra Indocabinet Tbk", logo: "https://assets.stockbit.com/logos/companies/WOOD.png" },
  ASHA: { name: "Cilacap Samudera Fishing Industry Tbk.", logo: "https://assets.stockbit.com/logos/companies/ASHA.png" },
  YELO: { name: "Yelooo Integra Datanet Tbk.", logo: "https://assets.stockbit.com/logos/companies/YELO.png" },
  VICI: { name: "Victoria Care Indonesia Tbk", logo: "https://assets.stockbit.com/logos/companies/VICI.png" },
  UVCR: { name: "Trimegah Karya Pratama Tbk.", logo: "https://assets.stockbit.com/logos/companies/UVCR.png" },
  UDNG: { name: "Agro Bahari Nusantara Tbk.", logo: "https://assets.stockbit.com/logos/companies/UDNG.png" },
  UNSP: { name: "Bakrie Sumatera Plantations Tbk.", logo: "https://assets.stockbit.com/logos/companies/UNSP.png" },
  PURA: { name: "Putra Rajawali Kencana Tbk.", logo: "https://assets.stockbit.com/logos/companies/PURA.png" },
  PGJO: { name: "Bahtera Bumi Raya Tbk", logo: "https://assets.stockbit.com/logos/companies/PGJO.png" },
  BAPA: { name: "Bekasi Asri Pemula Tbk.", logo: "https://assets.stockbit.com/logos/companies/BAPA.png" },
  AYLS: { name: "Agro Yasa Lestari Tbk.", logo: "https://assets.stockbit.com/logos/companies/AYLS.png" },
  ASRI: { name: "Alam Sutera Realty Tbk.", logo: "https://assets.stockbit.com/logos/companies/ASRI.png" },
  BVIC: { name: "Bank Victoria International Tbk.", logo: "https://assets.stockbit.com/logos/companies/BVIC.png" },
  DKHH: { name: "Cipta Sarana Medika Tbk.", logo: "https://assets.stockbit.com/logos/companies/DKHH.png?version=1745548095881785640" },
  ESTI: { name: "Ever Shine Tex Tbk.", logo: "https://assets.stockbit.com/logos/companies/ESTI.png" },
  DFAM: { name: "Dafam Property Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/DFAM.png" },
  DGIK: { name: "Nusa Konstruksi Enjiniring Tbk.", logo: "https://assets.stockbit.com/logos/companies/DGIK.png" },
  DGWG: { name: "Delta Giri Wacana Tbk.", logo: "https://assets.stockbit.com/logos/companies/DGWG.png?version=1733208765565022106" },
  TAYS: { name: "Jaya Swarasa Agung Tbk.", logo: "https://assets.stockbit.com/logos/companies/TAYS.png" },
  ESIP: { name: "Sinergi Inti Plastindo Tbk", logo: "https://assets.stockbit.com/logos/companies/ESIP.png" },
  DSFI: { name: "Dharma Samudera Fishing Industries Tbk.", logo: "https://assets.stockbit.com/logos/companies/DSFI.png" },
  CNKO: { name: "Exploitasi Energi Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/CNKO.png" },
  CRAB: { name: "Toba Surimi Industries Tbk.", logo: "https://assets.stockbit.com/logos/companies/CRAB.png" },
  DRMA: { name: "Dharma Polimetal Tbk.", logo: "https://assets.stockbit.com/logos/companies/DRMA.png" },
  CLAY: { name: "Citra Putra Realty Tbk.", logo: "https://assets.stockbit.com/logos/companies/CLAY.png" },
  CSMI: { name: "Cipta Selera Murni Tbk.", logo: "https://assets.stockbit.com/logos/companies/CSMI.png" },
  BOAT: { name: "Newport Marine Services Tbk.", logo: "https://assets.stockbit.com/logos/companies/BOAT.png?version=1729596081120361300" },
  IDEA: { name: "Idea Indonesia Akademi Tbk.", logo: "https://assets.stockbit.com/logos/companies/IDEA.png" },
  HEXA: { name: "Hexindo Adiperkasa Tbk.", logo: "https://assets.stockbit.com/logos/companies/HEXA.png" },
  GEMA: { name: "Gema Grahasarana Tbk.", logo: "https://assets.stockbit.com/logos/companies/GEMA.png?version=1734338430406011821" },
  ERTX: { name: "Eratex Djaja Tbk.", logo: "https://assets.stockbit.com/logos/companies/ERTX.png" },
  HBAT: { name: "Minahasa Membangun Hebat Tbk.", logo: "https://assets.stockbit.com/logos/companies/HBAT.png" },
  HDIT: { name: "Hensel Davest Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/HDIT.png" },
  GULA: { name: "Aman Agrindo Tbk.", logo: "https://assets.stockbit.com/logos/companies/GULA.png" },
  HAJJ: { name: "Arsy Buana Travelindo Tbk.", logo: "https://assets.stockbit.com/logos/companies/HAJJ.png" },
  HALO: { name: "Haloni Jane Tbk.", logo: "https://assets.stockbit.com/logos/companies/HALO.png" },
  INDX: { name: "Tanah Laut Tbk", logo: "https://assets.stockbit.com/logos/companies/INDX.png" },
  GSMF: { name: "Equity Development Investment Tbk.", logo: "https://assets.stockbit.com/logos/companies/GSMF.png" },
  GTRA: { name: "Grahaprima Suksesmandiri Tbk.", logo: "https://assets.stockbit.com/logos/companies/GTRA.png" },
  TMAS: { name: "Temas Tbk.", logo: "https://assets.stockbit.com/logos/companies/TMAS.png" },
  PRIM: { name: "Royal Prima Tbk.", logo: "https://assets.stockbit.com/logos/companies/PRIM.png" },
  PSAT: { name: "Pancaran Samudera Transport Tbk.", logo: "https://assets.stockbit.com/logos/companies/PSAT.png?version=1750651048942003364" },
  SPRE: { name: "Soraya Berjaya Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/SPRE.png" },
  PPRI: { name: "Paperocks Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/PPRI.png" },
  PTPS: { name: "Pulau Subur Tbk.", logo: "https://assets.stockbit.com/logos/companies/PTPS.png" },
  PRDA: { name: "Prodia Widyahusada Tbk", logo: "https://assets.stockbit.com/logos/companies/PRDA.png" },
  SATU: { name: "Kota Satu Properti Tbk.", logo: "https://assets.stockbit.com/logos/companies/SATU.png" },
  REAL: { name: "Repower Asia Indonesia Tbk", logo: "https://assets.stockbit.com/logos/companies/REAL.png" },
  IPCM: { name: "Jasa Armada Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/IPCM.png?version=1746788937071425779" },
  ISAP: { name: "Isra Presisi Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/ISAP.png" },
  STAR: { name: "Calculus Global Ventures Tbk.", logo: "https://assets.stockbit.com/logos/companies/STAR.png?version=1771997506800934603" },
  INOV: { name: "Inocycle Technology Group Tbk.", logo: "https://assets.stockbit.com/logos/companies/INOV.png" },
  IOTF: { name: "Sumber Sinergi Makmur Tbk.", logo: "https://assets.stockbit.com/logos/companies/IOTF.png" },
  IKAI: { name: "Intikeramik Alamasri Industri Tbk.", logo: "https://assets.stockbit.com/logos/companies/IKAI.png" },
  IKAN: { name: "Era Mandiri Cemerlang Tbk", logo: "https://assets.stockbit.com/logos/companies/IKAN.png" },
  SOHO: { name: "Soho Global Health Tbk", logo: "https://assets.stockbit.com/logos/companies/SOHO.png" },
  SOLA: { name: "Xolare RCR Energy Tbk.", logo: "https://assets.stockbit.com/logos/companies/SOLA.png" },
  KBLV: { name: "First Media Tbk.", logo: "https://assets.stockbit.com/logos/companies/KBLV.png" },
  KBAG: { name: "Karya Bersama Anugerah Tbk.", logo: "https://assets.stockbit.com/logos/companies/KBAG.png" },
  LOPI: { name: "Logisticsplus International Tbk.", logo: "https://assets.stockbit.com/logos/companies/LOPI.png" },
  LPCK: { name: "Lippo Cikarang Tbk", logo: "https://assets.stockbit.com/logos/companies/LPCK.png" },
  JMAS: { name: "Asuransi Jiwa Syariah Jasa Mitra Abadi Tbk", logo: "https://assets.stockbit.com/logos/companies/JMAS.png" },
  ISSP: { name: "Steel Pipe Industry Of Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/ISSP.png" },
  SNLK: { name: "Sunter Lakeside Hotel Tbk", logo: "https://assets.stockbit.com/logos/companies/SNLK.png" },
  LMAX: { name: "Lupromax Pelumas Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/LMAX.png" },
  MAYA: { name: "Bank Mayapada Internasional Tbk.", logo: "https://assets.stockbit.com/logos/companies/MAYA.png" },
  BMHS: { name: "Bundamedik Tbk", logo: "https://assets.stockbit.com/logos/companies/BMHS.png" },
  KLAS: { name: "Pelayaran Kurnia Lautan Semesta Tbk.", logo: "https://assets.stockbit.com/logos/companies/KLAS.png" },
  CGAS: { name: "Citra Nusantara Gemilang Tbk.", logo: "https://assets.stockbit.com/logos/companies/CGAS.png" },
  BMBL: { name: "Lavender Bina Cendikia Tbk.", logo: "https://assets.stockbit.com/logos/companies/BMBL.png" },
  SMBR: { name: "Semen Baturaja Tbk.", logo: "https://assets.stockbit.com/logos/companies/SMBR.png" },
  SMKM: { name: "Sumber Mas Konstruksi Tbk.", logo: "https://assets.stockbit.com/logos/companies/SMKM.png" },
  MANG: { name: "Manggung Polahraya Tbk.", logo: "https://assets.stockbit.com/logos/companies/MANG.png" },
  SLIS: { name: "Gaya Abadi Sempurna Tbk.", logo: "https://assets.stockbit.com/logos/companies/SLIS.png" },
  SGER: { name: "Sumber Global Energy Tbk", logo: "https://assets.stockbit.com/logos/companies/SGER.png" },
  KREN: { name: "Quantum Clovera Investama Tbk", logo: "https://assets.stockbit.com/logos/companies/KREN.png" },
  LABA: { name: "Green Power Group Tbk.", logo: "https://assets.stockbit.com/logos/companies/LABA.png?version=1723525059401828235" },
  MMIX: { name: "Multi Medika Internasional Tbk.", logo: "https://assets.stockbit.com/logos/companies/MMIX.png" },
  BBHI: { name: "Allo Bank Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/BBHI.png" },
  MGNA: { name: "Magna Investama Mandiri Tbk", logo: "https://assets.stockbit.com/logos/companies/MGNA.png" },
  MDRN: { name: "Modern Internasional Tbk.", logo: "https://assets.stockbit.com/logos/companies/MDRN.png" },
  MOLI: { name: "Madusari Murni Indah Tbk.", logo: "https://assets.stockbit.com/logos/companies/MOLI.png" },
  MINE: { name: "PT Sinar Terang Mandiri Tbk.", logo: "https://assets.stockbit.com/logos/companies/MINE.png?version=1740558107727099156" },
  MPIX: { name: "Mitra Pedagang Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/MPIX.png" },
  MPPA: { name: "Matahari Putra Prima Tbk.", logo: "https://assets.stockbit.com/logos/companies/MPPA.png" },
  NANO: { name: "Nanotech Indonesia Global Tbk.", logo: "https://assets.stockbit.com/logos/companies/NANO.png" },
  BEKS: { name: "Bank Pembangunan Daerah Banten Tbk.", logo: "https://assets.stockbit.com/logos/companies/BEKS.png" },
  BSBK: { name: "Wulandari Bangun Laksana Tbk.", logo: "https://assets.stockbit.com/logos/companies/BSBK.png" },
  PAMG: { name: "Bima Sakti Pertiwi Tbk.", logo: "https://assets.stockbit.com/logos/companies/PAMG.png" },
  PANR: { name: "Panorama Sentrawisata Tbk.", logo: "https://assets.stockbit.com/logos/companies/PANR.png" },
  BTEK: { name: "Bumi Teknokultura Unggul Tbk", logo: "https://assets.stockbit.com/logos/companies/BTEK.png" },
  BEEF: { name: "Estika Tata Tiara Tbk.", logo: "https://assets.stockbit.com/logos/companies/BEEF.png" },
  BACA: { name: "Bank Capital Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/BACA.png" },
  BBYB: { name: "Bank Neo Commerce Tbk.", logo: "https://assets.stockbit.com/logos/companies/BBYB.png" },
  PURI: { name: "Puri Global Sukses Tbk", logo: "https://assets.stockbit.com/logos/companies/PURI.png" },
  PTMP: { name: "Mitra Pack Tbk.", logo: "https://assets.stockbit.com/logos/companies/PTMP.png" },
  ASLC: { name: "Autopedia Sukses Lestari Tbk.", logo: "https://assets.stockbit.com/logos/companies/ASLC.png" },
  NTBK: { name: "Nusatama Berkah Tbk.", logo: "https://assets.stockbit.com/logos/companies/NTBK.png" },
  PART: { name: "Cipta Perdana Lancar Tbk", logo: "https://assets.stockbit.com/logos/companies/PART.png" },
  OKAS: { name: "Ancora Indonesia Resources Tbk.", logo: "https://assets.stockbit.com/logos/companies/OKAS.png" },
  OLIV: { name: "Oscar Mitra Sukses Sejahtera Tbk.", logo: "https://assets.stockbit.com/logos/companies/OLIV.png" },
  NICE: { name: "Adhi Kartiko Pratama Tbk.", logo: "https://assets.stockbit.com/logos/companies/NICE.png" },
  NELY: { name: "Pelayaran Nelly Dwi Putri Tbk.", logo: "https://assets.stockbit.com/logos/companies/NELY.png" },
  MUTU: { name: "Mutuagung Lestari Tbk.", logo: "https://assets.stockbit.com/logos/companies/MUTU.png" },
  VTNY: { name: "Venteny Fortuna International Tbk.", logo: "https://assets.stockbit.com/logos/companies/VTNY.png" },
  WINR: { name: "Winner Nusantara Jaya Tbk.", logo: "https://assets.stockbit.com/logos/companies/WINR.png" },
  AMAN: { name: "Makmur Berkah Amanda Tbk.", logo: "https://assets.stockbit.com/logos/companies/AMAN.png" },
  AMMS: { name: "Agung Menjangan Mas Tbk.", logo: "https://assets.stockbit.com/logos/companies/AMMS.png" },
  WINE: { name: "Hatten Bali Tbk.", logo: "https://assets.stockbit.com/logos/companies/WINE.png" },
  UNTD: { name: "Terang Dunia Internusa Tbk.", logo: "https://assets.stockbit.com/logos/companies/UNTD.png" },
  AEGS: { name: "Anugerah Spareparts Sejahtera Tbk.", logo: "https://assets.stockbit.com/logos/companies/AEGS.png" },
  PBRX: { name: "Pan Brothers Tbk.", logo: "https://assets.stockbit.com/logos/companies/PBRX.png" },
  PJHB: { name: "Pelayaran Jaya Hidup Baru Tbk.", logo: "https://assets.stockbit.com/logos/companies/PJHB.png?version=1761112492170410522" },
  ACRO: { name: "Samcro Hyosung Adilestari Tbk.", logo: "https://assets.stockbit.com/logos/companies/ACRO.png" },
  ACST: { name: "Acset Indonusa Tbk.", logo: "https://assets.stockbit.com/logos/companies/ACST.png" },
  ADMF: { name: "Adira Dinamika Multi Finance Tbk.", logo: "https://assets.stockbit.com/logos/companies/ADMF.png" },
  RLCO: { name: "Abadi Lestari Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/RLCO.png?version=1763973554054433286" },
  RAAM: { name: "Tripar Multivision Plus Tbk.", logo: "https://assets.stockbit.com/logos/companies/RAAM.png" },
  WOWS: { name: "Ginting Jaya Energi Tbk.", logo: "https://assets.stockbit.com/logos/companies/WOWS.png" },
  YOII: { name: "Asuransi Digital Bersama Tbk.", logo: "https://assets.stockbit.com/logos/companies/YOII.png?version=1733819717040304169" },
  UANG: { name: "Pakuan Tbk.", logo: "https://assets.stockbit.com/logos/companies/UANG.png" },
  AISA: { name: "FKS Food Sejahtera Tbk.", logo: "https://assets.stockbit.com/logos/companies/AISA.png" },
  ADHI: { name: "Adhi Karya (Persero) Tbk.", logo: "https://assets.stockbit.com/logos/companies/ADHI.png" },
  PKPK: { name: "Paragon Karya Perkasa Tbk", logo: "https://assets.stockbit.com/logos/companies/PKPK.png" },
  NINE: { name: "Techno9 Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/NINE.png" },
  PIPA: { name: "Multi Makmur Lemindo Tbk.", logo: "https://assets.stockbit.com/logos/companies/PIPA.png" },
  NEST: { name: "Esta Indonesia Tbk", logo: "https://assets.stockbit.com/logos/companies/NEST.png" },
  NETV: { name: "MDTV Media Technologies Tbk.", logo: "https://assets.stockbit.com/logos/companies/NETV.png?version=1766556246801592606" },
  MSKY: { name: "MNC Sky Vision Tbk.", logo: "https://assets.stockbit.com/logos/companies/MSKY.png" },
  MITI: { name: "Mitra Investindo Tbk", logo: "https://assets.stockbit.com/logos/companies/MITI.png" },
  MGRO: { name: "Mahkota Group Tbk.", logo: "https://assets.stockbit.com/logos/companies/MGRO.png" },
  MEJA: { name: "Harta Djaya Karya Tbk.", logo: "https://assets.stockbit.com/logos/companies/MEJA.png" },
  SMGA: { name: "Sumber Mineral Global Abadi Tbk.", logo: "https://assets.stockbit.com/logos/companies/SMGA.png" },
  KOCI: { name: "Kokoh Exa Nusantara Tbk.", logo: "https://assets.stockbit.com/logos/companies/KOCI.png" },
  MDIY: { name: "Daya Intiguna Yasa Tbk.", logo: "https://assets.stockbit.com/logos/companies/MDIY.png?version=1732771500426563859" },
  MAIN: { name: "Malindo Feedmill Tbk.", logo: "https://assets.stockbit.com/logos/companies/MAIN.png" },
  JKON: { name: "Jaya Konstruksi Manggala Pratama Tbk.", logo: "https://assets.stockbit.com/logos/companies/JKON.png" },
  JATI: { name: "Informasi Teknologi Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/JATI.png" },
  INTP: { name: "Indocement Tunggal Prakarsa Tbk.", logo: "https://assets.stockbit.com/logos/companies/INTP.png" },
  KIOS: { name: "Kioson Komersial Indonesia Tbk", logo: "https://assets.stockbit.com/logos/companies/KIOS.png" },
  KJEN: { name: "Krida Jaringan Nusantara Tbk.", logo: "https://assets.stockbit.com/logos/companies/KJEN.png" },
  SQMI: { name: "Wilton Makmur Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/SQMI.png" },
  SRTG: { name: "Saratoga Investama Sedaya Tbk.", logo: "https://assets.stockbit.com/logos/companies/SRTG.png" },
  SSMS: { name: "Sawit Sumbermas Sarana Tbk.", logo: "https://assets.stockbit.com/logos/companies/SSMS.png" },
  RMKE: { name: "RMK Energy Tbk.", logo: "https://assets.stockbit.com/logos/companies/RMKE.png" },
  IMJS: { name: "Indomobil Multi Jasa Tbk.", logo: "https://assets.stockbit.com/logos/companies/IMJS.png" },
  FIRE: { name: "Alfa Energi Investama Tbk", logo: "https://assets.stockbit.com/logos/companies/FIRE.png" },
  HOKI: { name: "Buyung Poetra Sembada Tbk", logo: "https://assets.stockbit.com/logos/companies/HOKI.png" },
  HOPE: { name: "Harapan Duta Pertiwi Tbk.", logo: "https://assets.stockbit.com/logos/companies/HOPE.png" },
  HATM: { name: "Habco Trans Maritima Tbk.", logo: "https://assets.stockbit.com/logos/companies/HATM.png" },
  GPSO: { name: "Geoprima Solusi Tbk.", logo: "https://assets.stockbit.com/logos/companies/GPSO.png" },
  DSNG: { name: "Dharma Satya Nusantara Tbk.", logo: "https://assets.stockbit.com/logos/companies/DSNG.png" },
  TAXI: { name: "Express Transindo Utama Tbk.", logo: "https://assets.stockbit.com/logos/companies/TAXI.png" },
  CSRA: { name: "Cisadane Sawit Raya Tbk", logo: "https://assets.stockbit.com/logos/companies/CSRA.png" },
  CITA: { name: "Cita Mineral Investindo Tbk.", logo: "https://assets.stockbit.com/logos/companies/CITA.png" },
  BWPT: { name: "Eagle High Plantations Tbk.", logo: "https://assets.stockbit.com/logos/companies/BWPT.png" },
  TOOL: { name: "Rohartindo Nusantara Luas Tbk.", logo: "https://assets.stockbit.com/logos/companies/TOOL.png" },
  CARS: { name: "Industri dan Perdagangan Bintraco Dharma Tbk.", logo: "https://assets.stockbit.com/logos/companies/CARS.png" },
  BIKE: { name: "Sepeda Bersama Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/BIKE.png" },
  BRRC: { name: "Raja Roti Cemerlang Tbk.", logo: "https://assets.stockbit.com/logos/companies/BRRC.png?version=1734503531199888409" },
  BABY: { name: "Multitrend Indo Tbk.", logo: "https://assets.stockbit.com/logos/companies/BABY.png" },
  BAIK: { name: "Bersama Mencapai Puncak Tbk.", logo: "https://assets.stockbit.com/logos/companies/BAIK.png" },
  BKSW: { name: "Bank QNB Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/BKSW.png" },
  WTON: { name: "Wijaya Karya Beton Tbk", logo: "https://assets.stockbit.com/logos/companies/WTON.png" },
  RMKO: { name: "Royaltama Mulia Kontraktorindo Tbk.", logo: "https://assets.stockbit.com/logos/companies/RMKO.png" },
  TBLA: { name: "Tunas Baru Lampung Tbk.", logo: "https://assets.stockbit.com/logos/companies/TBLA.png" },
  KUAS: { name: "Ace Oldfields Tbk.", logo: "https://assets.stockbit.com/logos/companies/KUAS.png" },
  KRAS: { name: "Krakatau Steel (Persero) Tbk.", logo: "https://assets.stockbit.com/logos/companies/KRAS.png" },
  MORA: { name: "Mora Telematika Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/MORA.png" },
  SMIL: { name: "Sarana Mitra Luas Tbk.", logo: "https://assets.stockbit.com/logos/companies/SMIL.png" },
  MTFN: { name: "Capitalinc Investment Tbk.", logo: "https://assets.stockbit.com/logos/companies/MTFN.png" },
  PACK: { name: "Abadi Nusantara Hijau Investama Tbk", logo: "https://assets.stockbit.com/logos/companies/PACK.png" },
  MTDL: { name: "Metrodata Electronics Tbk.", logo: "https://assets.stockbit.com/logos/companies/MTDL.png" },
  PSDN: { name: "Prasidha Aneka Niaga Tbk", logo: "https://assets.stockbit.com/logos/companies/PSDN.png" },
  BSSR: { name: "Baramulti Suksessarana Tbk.", logo: "https://assets.stockbit.com/logos/companies/BSSR.png" },
  TEBE: { name: "Dana Brata Luhur Tbk", logo: "https://assets.stockbit.com/logos/companies/TEBE.png" },
  TUGU: { name: "Asuransi Tugu Pratama Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/TUGU.png" },
  UNVR: { name: "Unilever Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/UNVR.png" },
  ATLA: { name: "Atlantis Subsea Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/ATLA.png" },
  COAL: { name: "Black Diamond Resources Tbk.", logo: "https://assets.stockbit.com/logos/companies/COAL.png" },
  ELPI: { name: "Pelayaran Nasional Ekalya Purnamasari Tbk.", logo: "https://assets.stockbit.com/logos/companies/ELPI.png" },
  GPRA: { name: "Perdana Gapuraprima Tbk.", logo: "https://assets.stockbit.com/logos/companies/GPRA.png" },
  BLTA: { name: "Berlian Laju Tanker Tbk", logo: "https://assets.stockbit.com/logos/companies/BLTA.png" },
  BLUE: { name: "Berkah Prima Perkasa Tbk.", logo: "https://assets.stockbit.com/logos/companies/BLUE.png" },
  DOID: { name: "BUMA Internasional Grup Tbk.", logo: "https://assets.stockbit.com/logos/companies/DOID.png" },
  ATAP: { name: "Trimitra Prawara Goldland Tbk", logo: "https://assets.stockbit.com/logos/companies/ATAP.png" },
  TRUE: { name: "Triniti Dinamik Tbk", logo: "https://assets.stockbit.com/logos/companies/TRUE.png?version=1763365899309126842" },
  MBSS: { name: "Mitrabahtera Segara Sejati Tbk.", logo: "https://assets.stockbit.com/logos/companies/MBSS.png" },
  SMAR: { name: "Sinar Mas Agro Resources and Technology Tbk", logo: "https://assets.stockbit.com/logos/companies/SMAR.png" },
  LAJU: { name: "Jasa Berdikari Logistics Tbk.", logo: "https://assets.stockbit.com/logos/companies/LAJU.png" },
  AHAP: { name: "Asuransi Harta Aman Pratama Tbk.", logo: "https://assets.stockbit.com/logos/companies/AHAP.png" },
  VISI: { name: "Satu Visi Putra Tbk.", logo: "https://assets.stockbit.com/logos/companies/VISI.png" },
  SILO: { name: "Siloam International Hospitals Tbk", logo: "https://assets.stockbit.com/logos/companies/SILO.png" },
  SUPA: { name: "Super Bank Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/SUPA.png?version=1764033894732191693" },
  WIRG: { name: "Wir Asia Tbk.", logo: "https://assets.stockbit.com/logos/companies/WIRG.png" },
  CPRO: { name: "Central Proteina Prima Tbk", logo: "https://assets.stockbit.com/logos/companies/CPRO.png" },
  ELSA: { name: "Elnusa Tbk.", logo: "https://assets.stockbit.com/logos/companies/ELSA.png" },
  BBKP: { name: "Bank KB Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/BBKP.png" },
  MIKA: { name: "PT Mitra Keluarga Karyasehat Tbk.", logo: "https://assets.stockbit.com/logos/companies/MIKA.png" },
  PADI: { name: "Minna Padi Investama Sekuritas Tbk.", logo: "https://assets.stockbit.com/logos/companies/PADI.png" },
  PYFA: { name: "Pyridam Farma Tbk", logo: "https://assets.stockbit.com/logos/companies/PYFA.png" },
  HRUM: { name: "Harum Energy Tbk.", logo: "https://assets.stockbit.com/logos/companies/HRUM.png" },
  IBOS: { name: "Indo Boga Sukses Tbk.", logo: "https://assets.stockbit.com/logos/companies/IBOS.png" },
  TBIG: { name: "Tower Bersama Infrastructure Tbk.", logo: "https://assets.stockbit.com/logos/companies/TBIG.png" },
  BKSL: { name: "Sentul City Tbk.", logo: "https://assets.stockbit.com/logos/companies/BKSL.png" },
  DILD: { name: "Intiland Development Tbk.", logo: "https://assets.stockbit.com/logos/companies/DILD.png" },
  HUMI: { name: "Humpuss Maritim Internasional Tbk.", logo: "https://assets.stockbit.com/logos/companies/HUMI.png" },
  DATA: { name: "Remala Abadi Tbk.", logo: "https://assets.stockbit.com/logos/companies/DATA.png" },
  TRIN: { name: "Perintis Triniti Properti Tbk", logo: "https://assets.stockbit.com/logos/companies/TRIN.png?version=1763365886868768536" },
  MAHA: { name: "Mandiri Herindo Adiperkasa Tbk.", logo: "https://assets.stockbit.com/logos/companies/MAHA.png" },
  BNGA: { name: "Bank CIMB Niaga Tbk.", logo: "https://assets.stockbit.com/logos/companies/BNGA.png" },
  TOBA: { name: "TBS Energi Utama Tbk", logo: "https://assets.stockbit.com/logos/companies/TOBA.png?version=1770367590961892787" },
  APEX: { name: "Apexindo Pratama Duta Tbk", logo: "https://assets.stockbit.com/logos/companies/APEX.png" },
  ICBP: { name: "Indofood CBP Sukses Makmur Tbk.", logo: "https://assets.stockbit.com/logos/companies/ICBP.png" },
  AVIA: { name: "Avia Avian Tbk.", logo: "https://assets.stockbit.com/logos/companies/AVIA.png" },
  STAA: { name: "Sumber Tani Agung Resources Tbk.", logo: "https://assets.stockbit.com/logos/companies/STAA.png?ver=2" },
  JGLE: { name: "Graha Andrasentra Propertindo Tbk.", logo: "https://assets.stockbit.com/logos/companies/JGLE.png" },
  NICL: { name: "PAM Mineral Tbk.", logo: "https://assets.stockbit.com/logos/companies/NICL.png" },
  PGEO: { name: "Pertamina Geothermal Energy Tbk.", logo: "https://assets.stockbit.com/logos/companies/PGEO.png" },
  ARKO: { name: "Arkora Hydro Tbk.", logo: "https://assets.stockbit.com/logos/companies/ARKO.png" },
  BSDE: { name: "Bumi Serpong Damai Tbk.", logo: "https://assets.stockbit.com/logos/companies/BSDE.png" },
  MIDI: { name: "Midi Utama Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/MIDI.png" },
  KAQI: { name: "Jantra Grupo Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/KAQI.png?version=1740535501971709150" },
  CMRY: { name: "Cisarua Mountain Dairy Tbk.", logo: "https://assets.stockbit.com/logos/companies/CMRY.png" },
  BIPI: { name: "Astrindo Nusantara Infrastruktur Tbk.", logo: "https://assets.stockbit.com/logos/companies/BIPI.png" },
  INCO: { name: "Vale Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/INCO.png" },
  BUKA: { name: "Bukalapak.com Tbk.", logo: "https://assets.stockbit.com/logos/companies/BUKA.png" },
  IRSX: { name: "Folago Global Nusantara Tbk.", logo: "https://assets.stockbit.com/logos/companies/IRSX.png" },
  HMSP: { name: "H.M. Sampoerna Tbk.", logo: "https://assets.stockbit.com/logos/companies/HMSP.png" },
  SMRA: { name: "Summarecon Agung Tbk.", logo: "https://assets.stockbit.com/logos/companies/SMRA.png" },
  ELTY: { name: "Bakrieland Development Tbk.", logo: "https://assets.stockbit.com/logos/companies/ELTY.png" },
  MAPA: { name: "Map Aktif Adiperkasa Tbk.", logo: "https://assets.stockbit.com/logos/companies/MAPA.png" },
  RALS: { name: "Ramayana Lestari Sentosa Tbk.", logo: "https://assets.stockbit.com/logos/companies/RALS.png" },
  SOCI: { name: "Soechi Lines Tbk.", logo: "https://assets.stockbit.com/logos/companies/SOCI.png" },
  BUVA: { name: "Bukit Uluwatu Villa Tbk.", logo: "https://assets.stockbit.com/logos/companies/BUVA.png" },
  KLBF: { name: "Kalbe Farma Tbk.", logo: "https://assets.stockbit.com/logos/companies/KLBF.png" },
  JSMR: { name: "Jasa Marga (Persero) Tbk.", logo: "https://assets.stockbit.com/logos/companies/JSMR.png" },
  WIFI: { name: "Solusi Sinergi Digital Tbk", logo: "https://assets.stockbit.com/logos/companies/WIFI.png" },
  MINA: { name: "Sanurhasta Mitra Tbk", logo: "https://assets.stockbit.com/logos/companies/MINA.png" },
  KIJA: { name: "Kawasan Industri Jababeka Tbk.", logo: "https://assets.stockbit.com/logos/companies/KIJA.png" },
  SMDR: { name: "Samudera Indonesia  Tbk.", logo: "https://assets.stockbit.com/logos/companies/SMDR.png" },
  MAPI: { name: "Mitra Adiperkasa Tbk.", logo: "https://assets.stockbit.com/logos/companies/MAPI.png" },
  FILM: { name: "MD Entertainment Tbk", logo: "https://assets.stockbit.com/logos/companies/FILM.png?version=1732771253362244739" },
  MMLP: { name: "Mega Manunggal Property Tbk.", logo: "https://assets.stockbit.com/logos/companies/MMLP.png" },
  WIIM: { name: "PT Wismilak Inti Makmur Tbk.", logo: "https://assets.stockbit.com/logos/companies/WIIM.png" },
  CBDK: { name: "Bangun Kosambi Sukses Tbk", logo: "https://assets.stockbit.com/logos/companies/CBDK.png?version=1734058949472712899" },
  LSIP: { name: "PP London Sumatra Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/LSIP.png" },
  CPIN: { name: "Charoen Pokphand Indonesia Tbk", logo: "https://assets.stockbit.com/logos/companies/CPIN.png" },
  EMAS: { name: "Merdeka Gold Resources Tbk.", logo: "https://assets.stockbit.com/logos/companies/EMAS.png?version=1757313721556982559" },
  AMRT: { name: "Sumber Alfaria Trijaya Tbk.", logo: "https://assets.stockbit.com/logos/companies/AMRT.png" },
  DEWA: { name: "Darma Henwa Tbk", logo: "https://assets.stockbit.com/logos/companies/DEWA.png?version=1731380794259246908" },
  AMMN: { name: "Amman Mineral Internasional Tbk.", logo: "https://assets.stockbit.com/logos/companies/AMMN.png?version=1723524843327460802" },
  MDKA: { name: "Merdeka Copper Gold Tbk.", logo: "https://assets.stockbit.com/logos/companies/MDKA.png" },
  AADI: { name: "Adaro Andalan Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/AADI.png?version=1731380937972873322" },
  GOTO: { name: "GoTo Gojek Tokopedia Tbk.", logo: "https://assets.stockbit.com/logos/companies/GOTO.png" },
  INKP: { name: "Indah Kiat Pulp & Paper Tbk.", logo: "https://assets.stockbit.com/logos/companies/INKP.png" },
  MEDC: { name: "Medco Energi Internasional Tbk", logo: "https://assets.stockbit.com/logos/companies/MEDC.png" },
  PTRO: { name: "Petrosea Tbk.", logo: "https://assets.stockbit.com/logos/companies/PTRO.png" },
  ESSA: { name: "ESSA Industries Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/ESSA.png" },
  BBNI: { name: "Bank Negara Indonesia (Persero) Tbk.", logo: "https://assets.stockbit.com/logos/companies/BBNI.png" },
  INDY: { name: "Indika Energy Tbk.", logo: "https://assets.stockbit.com/logos/companies/INDY.png" },
  BBCA: { name: "Bank Central Asia Tbk.", logo: "https://assets.stockbit.com/logos/companies/BBCA.png" },
  ENRG: { name: "Energi Mega Persada Tbk.", logo: "https://assets.stockbit.com/logos/companies/ENRG.png?version=1750036449822958153" },
  BBRI: { name: "Bank Rakyat Indonesia (Persero) Tbk.", logo: "https://assets.stockbit.com/logos/companies/BBRI.png" },
  BMRI: { name: "Bank Mandiri (Persero) Tbk.", logo: "https://assets.stockbit.com/logos/companies/BMRI.png" },
  EXCL: { name: "XLSMART Telecom Sejahtera Tbk.", logo: "https://assets.stockbit.com/logos/companies/EXCL.png?version=1747296040608163618" },
  ANTM: { name: "Aneka Tambang Tbk.", logo: "https://assets.stockbit.com/logos/companies/ANTM.png" },
  TINS: { name: "Timah Tbk.", logo: "https://assets.stockbit.com/logos/companies/TINS.png" },
  IMPC: { name: "Impack Pratama Industri Tbk.", logo: "https://assets.stockbit.com/logos/companies/IMPC.png?version=1742443117317841833" },
  UNTR: { name: "United Tractors Tbk.", logo: "https://assets.stockbit.com/logos/companies/UNTR.png" },
  CDIA: { name: "Chandra Daya Investasi Tbk.", logo: "https://assets.stockbit.com/logos/companies/CDIA.png?version=1750294950929128288" },
  RATU: { name: "Raharja Energi Cepu Tbk.", logo: "https://assets.stockbit.com/logos/companies/RATU.png?version=1734335521561381591" },
  EURO: { name: "Estee Gold Feet Tbk.", logo: "https://assets.stockbit.com/logos/companies/EURO.png" },
  ADMR: { name: "Alamtri Minerals Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/ADMR.png?version=1753857326844772768" },
  BUMI: { name: "Bumi Resources Tbk", logo: "https://assets.stockbit.com/logos/companies/BUMI.png?version=1773298968177939377" },
  JPFA: { name: "Japfa Comfeed Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/JPFA.png" },
  ADRO: { name: "Alamtri Resources Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/ADRO.png?version=1753857016610110434" },
  SGRO: { name: "Prime Agri Resources Tbk.", logo: "https://assets.stockbit.com/logos/companies/SGRO.png?version=1768378226959124921" },
  INET: { name: "Sinergi Inti Andalan Prima Tbk.", logo: "https://assets.stockbit.com/logos/companies/INET.png" },
  PANI: { name: "Pantai Indah Kapuk Dua Tbk.", logo: "https://assets.stockbit.com/logos/companies/PANI.png?version=1724730260229025769" },
  SMSM: { name: "Selamat Sempurna Tbk.", logo: "https://assets.stockbit.com/logos/companies/SMSM.png" },
  BJTM: { name: "Bank Pembangunan Daerah Jawa Timur Tbk.", logo: "https://assets.stockbit.com/logos/companies/BJTM.png" },
  SSIA: { name: "Surya Semesta Internusa Tbk.", logo: "https://assets.stockbit.com/logos/companies/SSIA.png" },
  ASSA: { name: "Adi Sarana Armada Tbk.", logo: "https://assets.stockbit.com/logos/companies/ASSA.png" },
  LPPF: { name: "Matahari Department Store Tbk.", logo: "https://assets.stockbit.com/logos/companies/LPPF.png" },
  DKFT: { name: "Central Omega Resources Tbk.", logo: "https://assets.stockbit.com/logos/companies/DKFT.png" },
  NOBU: { name: "Bank Nationalnobu Tbk.", logo: "https://assets.stockbit.com/logos/companies/NOBU.png" },
  VKTR: { name: "VKTR Teknologi Mobilitas Tbk.", logo: "https://assets.stockbit.com/logos/companies/VKTR.png" },
  CYBR: { name: "ITSEC Asia Tbk.", logo: "https://assets.stockbit.com/logos/companies/CYBR.png" },
  OASA: { name: "Maharaksa Biru Energi Tbk.", logo: "https://assets.stockbit.com/logos/companies/OASA.png?version=1771926277396885027" },
  PBSA: { name: "Paramita Bangun Sarana Tbk.", logo: "https://assets.stockbit.com/logos/companies/PBSA.png" },
  GMFI: { name: "Garuda Maintenance Facility Aero Asia Tbk", logo: "https://assets.stockbit.com/logos/companies/GMFI.png" },
  TOWR: { name: "Sarana Menara Nusantara Tbk.", logo: "https://assets.stockbit.com/logos/companies/TOWR.png" },
  BJBR: { name: "Bank Pembangunan Daerah Jawa Barat dan Banten Tbk", logo: "https://assets.stockbit.com/logos/companies/BJBR.png?ver=1" },
  CARE: { name: "Metro Healthcare Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/CARE.png" },
  TCPI: { name: "Transcoal Pacific Tbk.", logo: "https://assets.stockbit.com/logos/companies/TCPI.png" },
  KEEN: { name: "Kencana Energi Lestari Tbk.", logo: "https://assets.stockbit.com/logos/companies/KEEN.png" },
  ABMM: { name: "ABM Investama Tbk.", logo: "https://assets.stockbit.com/logos/companies/ABMM.png" },
  MSJA: { name: "Multi Spunindo Jaya Tbk.", logo: "https://assets.stockbit.com/logos/companies/MSJA.png" },
  FORE: { name: "Fore Kopi Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/FORE.png?version=1742372063933187602" },
  DEWI: { name: "Dewi Shri Farmindo Tbk.", logo: "https://assets.stockbit.com/logos/companies/DEWI.png" },
  FPNI: { name: "Lotte Chemical Titan Tbk.", logo: "https://assets.stockbit.com/logos/companies/FPNI.png" },
  HOMI: { name: "Grand House Mulia Tbk", logo: "https://assets.stockbit.com/logos/companies/HOMI.png" },
  MPMX: { name: "Mitra Pinasthika Mustika Tbk.", logo: "https://assets.stockbit.com/logos/companies/MPMX.png" },
  AUTO: { name: "Astra Otoparts Tbk.", logo: "https://assets.stockbit.com/logos/companies/AUTO.png" },
  JTPE: { name: "Jasuindo Tiga Perkasa Tbk.", logo: "https://assets.stockbit.com/logos/companies/JTPE.png" },
  CUAN: { name: "Petrindo Jaya Kreasi Tbk.", logo: "https://assets.stockbit.com/logos/companies/CUAN.png" },
  ARCI: { name: "Archi Indonesia Tbk", logo: "https://assets.stockbit.com/logos/companies/ARCI.png" },
  TPIA: { name: "Chandra Asri Pacific Tbk.", logo: "https://assets.stockbit.com/logos/companies/TPIA.png?version=1750055121325821609" },
  TAPG: { name: "Triputra Agro Persada Tbk", logo: "https://assets.stockbit.com/logos/companies/TAPG.png" },
  BRMS: { name: "Bumi Resources Minerals Tbk.", logo: "https://assets.stockbit.com/logos/companies/BRMS.png" },
  BBTN: { name: "Bank Tabungan Negara (Persero) Tbk.", logo: "https://assets.stockbit.com/logos/companies/BBTN.png" },
  SMGR: { name: "Semen Indonesia (Persero) Tbk.", logo: "https://assets.stockbit.com/logos/companies/SMGR.png" },
  INDS: { name: "Indospring Tbk.", logo: "https://assets.stockbit.com/logos/companies/INDS.png" },
  MSIN: { name: "MNC Digital Entertainment Tbk.", logo: "https://assets.stockbit.com/logos/companies/MSIN.png?version=1770367821463423354" },
  BNBR: { name: "Bakrie & Brothers Tbk", logo: "https://assets.stockbit.com/logos/companies/BNBR.png" },
  COIN: { name: "Indokripto Koin Semesta Tbk", logo: "https://assets.stockbit.com/logos/companies/COIN.png?version=1750643999108901654" },
  SOFA: { name: "Solusi Environment Asia Tbk.", logo: "https://assets.stockbit.com/logos/companies/SOFA.png?version=1769138923674809807" },
  PTPP: { name: "PP (Persero) Tbk.", logo: "https://assets.stockbit.com/logos/companies/PTPP.png" },
  HRTA: { name: "Hartadinata Abadi Tbk", logo: "https://assets.stockbit.com/logos/companies/HRTA.png" },
  PSKT: { name: "Red Planet Indonesia Tbk.", logo: "https://assets.stockbit.com/logos/companies/PSKT.png" },
  CBRE: { name: "Cakra Buana Resources Energi Tbk.", logo: "https://assets.stockbit.com/logos/companies/CBRE.png" },
  TSPC: { name: "Tempo Scan Pacific Tbk.", logo: "https://assets.stockbit.com/logos/companies/TSPC.png" },
  EMTK: { name: "Elang Mahkota Teknologi Tbk.", logo: "https://assets.stockbit.com/logos/companies/EMTK.png" },
  ASLI: { name: "Asri Karya Lestari Tbk.", logo: "https://assets.stockbit.com/logos/companies/ASLI.png?version=1723112541636503996" },
  SIMP: { name: "Salim Ivomas Pratama Tbk.", logo: "https://assets.stockbit.com/logos/companies/SIMP.png" },
  COCO: { name: "Wahana Interfood Nusantara Tbk.", logo: "https://assets.stockbit.com/logos/companies/COCO.png" },
  SIDO: { name: "Industri Jamu dan Farmasi Sido Muncul Tbk", logo: "https://assets.stockbit.com/logos/companies/SIDO.png" },
  FUTR: { name: "Futura Energi Global Tbk.", logo: "https://assets.stockbit.com/logos/companies/FUTR.png?version=1741669918103381367" },
  GOLF: { name: "Intra GolfLink Resorts Tbk", logo: "https://assets.stockbit.com/logos/companies/GOLF.png" },
  LPKR: { name: "Lippo Karawaci Tbk.", logo: "https://assets.stockbit.com/logos/companies/LPKR.png" },
  GZCO: { name: "Gozco Plantations Tbk.", logo: "https://assets.stockbit.com/logos/companies/GZCO.png" },
  ULTJ: { name: "Ultra Jaya Milk Industry & Trading Company Tbk.", logo: "https://assets.stockbit.com/logos/companies/ULTJ.png" },
  RISE: { name: "Jaya Sukses Makmur Sentosa Tbk.", logo: "https://assets.stockbit.com/logos/companies/RISE.png" },
  ASGR: { name: "Astra Graphia Tbk.", logo: "https://assets.stockbit.com/logos/companies/ASGR.png" },
  NPGF: { name: "Nusa Palapa Gemilang Tbk.", logo: "https://assets.stockbit.com/logos/companies/NPGF.png" },
  MTEL: { name: "Dayamitra Telekomunikasi Tbk.", logo: "https://assets.stockbit.com/logos/companies/MTEL.png" },
  PPRO: { name: "PT PP Property Tbk.", logo: "https://assets.stockbit.com/logos/companies/PPRO.png" },
  LPPS: { name: "Lenox Pasifik Investama Tbk.", logo: "https://assets.stockbit.com/logos/companies/LPPS.png" },
};

export const tickers = Object.keys(tickerData);

export function getTickerInfo(symbol: string): TickerInfo | undefined {
  return tickerData[symbol];
}

export default tickers;
